In [3]:
import pandas as pd
import numpy as np
import re

In [4]:
df = pd.read_csv("laptop_raw_data.csv")

In [5]:
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...
...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...

In [6]:
df["Product Feature"].iloc[0]

'Snapdragon X Elite Processor16 GB LPDDR5X RAMWindows 11 Operating System512 GB SSD38.1 cm (15 Inch) Touchscreen Display1 Year Onsite Warranty'

In [7]:
data = ''' 
Intel Celeron Quad Core Processor (12th Gen)8 GB LPDDR5 RAM64 bit Windows 11 Home Operating System256 GB SSD35.81 cm (14.1 inch) DisplayWPS Office, Operating System Software1 Year Onsite Warranty
Intel Core i5 Processor (12th Gen)16 GB DDR4 RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) Display1 Year Onsite Warranty
MediaTek Kompanio 520 Processor4 GB LPDDR4X RAMChrome Operating System29.46 cm (11.6 Inch) Display1 Year Carry-in Warranty
AMD Ryzen 7 Octa Core Processor16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Carry-in Warranty
Intel Celeron Dual Core Processor8 GB DDR4 RAM64 bit Windows 11 Home Operating System512 GB SSD29.46 cm (11.6 inch) Display1 Year Warranty
Intel Celeron Dual Core Processor8 GB LPDDR4X RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) Display1 Year International Travelers Warranty (ITW)
Intel Celeron Dual Core Processor8 GB DDR4 RAM64 bit Windows 11 Home Operating System256 GB SSD29.46 cm (11.6 inch) Display1 Year Warranty
MediaTek MediaTek Kompanio 838 Processor8 GB LPDDR4X RAMChrome Operating System70.64 cm (27.81 cm) Touchscreen Display1 Year Onsite Warranty
Intel Core i3 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Carry-in Warranty
Intel Core i3 Processor (12th Gen)8 GB DDR4 RAM64 bit Windows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Domestic Warranty
Intel Core i3 Processor (13th Gen)8 GB DDR4 RAM64 bit Windows 11 Home Operating System256 GB SSD35.56 cm (14 inch) Display1 Year Warranty
AMD Ryzen 5 Hexa Core Processor16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Carry-in Warranty
Intel Core i3 Processor (13th Gen)8 GB LPDDR4X RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Onsite Warranty
Intel Core i5 Processor (12th Gen)16 GB LPDDR5 RAM64 bit Windows 11 Home Operating System1 TB SSD39.62 cm (15.6 inch) Display1 Year Onsite warranty
Intel Core i5 Processor (13th Gen)16 GB DDR5 RAMWindows 11 Home Operating System512 GB SSD35.56 cm (14 inch) DisplayMicrosoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps, McAfee 1 year1 Year Onsite Warranty
MediaTek MediaTek Kompanio 528 Processor4 GB LPDDR4X RAMChrome Operating System29.46 cm (11.6 Inch) Display1 Year Carry-in Warranty
Intel Core i7 Processor (12th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD35.56 cm (14 inch) Display1 Year Warranty Term
Intel Core i5 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) DisplayWindows 11 and Microsoft Office Home & Student Edition 20241 Year Carry-in Warranty
Intel Core i5 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Onsite Warranty
Intel Celeron Dual Core Processor8 GB LPDDR4X RAMWindows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Carry-in Warranty'''

In [8]:
# Processor
pattern = r'(?:Intel|MediaTek|Snapdragon|Apple|AMD)[\s\w]+Processor(?:\s\([\d+\w+\s]+\))?'

word= re.findall(pattern, data)
word

['Intel Celeron Quad Core Processor (12th Gen)',
 'Intel Core i5 Processor (12th Gen)',
 'MediaTek Kompanio 520 Processor',
 'AMD Ryzen 7 Octa Core Processor',
 'Intel Celeron Dual Core Processor',
 'Intel Celeron Dual Core Processor',
 'Intel Celeron Dual Core Processor',
 'MediaTek MediaTek Kompanio 838 Processor',
 'Intel Core i3 Processor (13th Gen)',
 'Intel Core i3 Processor (12th Gen)',
 'Intel Core i3 Processor (13th Gen)',
 'AMD Ryzen 5 Hexa Core Processor',
 'Intel Core i3 Processor (13th Gen)',
 'Intel Core i5 Processor (12th Gen)',
 'Intel Core i5 Processor (13th Gen)',
 'MediaTek MediaTek Kompanio 528 Processor',
 'Intel Core i7 Processor (12th Gen)',
 'Intel Core i5 Processor (13th Gen)',
 'Intel Core i5 Processor (13th Gen)',
 'Intel Celeron Dual Core Processor']

In [9]:
len(word)

20

In [10]:
# RAM
pattern = r"\d+\sGB[\s\w]*RAM" 
ram = re.findall(pattern, data)
ram, len(ram)

(['8 GB LPDDR5 RAM',
  '16 GB DDR4 RAM',
  '4 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '8 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '16 GB LPDDR5 RAM',
  '16 GB DDR5 RAM',
  '4 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '8 GB LPDDR4X RAM'],
 20)

In [11]:
# OS

pattern = r'(?:Windows|Chrome|MacOs)[\s\w]+Operating\sSystem'
os = re.findall(pattern, data)
os, len(os)

(['Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System'],
 20)

In [12]:
# Storage
pattern = r'\d+\s(?:GB|TB)\s(?:SSD|HDD)'
storage = re.findall(pattern, data)
storage,len(storage)

(['256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '1 TB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD'],
 17)

In [13]:
# Display
pattern = r'\d+\.\d+\scm.*Display'
display = re.findall(pattern, data)
display, len(display)

(['35.81 cm (14.1 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '29.46 cm (11.6 Inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '29.46 cm (11.6 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '29.46 cm (11.6 inch) Display',
  '70.64 cm (27.81 cm) Touchscreen Display',
  '35.56 cm (14 Inch) Display',
  '35.56 cm (14 Inch) Display',
  '35.56 cm (14 inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '39.62 cm (15.6 inch) Display',
  '35.56 cm (14 inch) Display',
  '29.46 cm (11.6 Inch) Display',
  '35.56 cm (14 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '35.56 cm (14 Inch) Display'],
 20)

In [14]:
# Warranty

pattern = r'\d\sY[Year|Years]+[\s\-\w]*(?:warranty|Warranty)'
warranty = re.findall(pattern, data)
warranty , len(warranty)

(['1 Year Onsite Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Warranty',
  '1 Year International Travelers Warranty',
  '1 Year Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Domestic Warranty',
  '1 Year Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Onsite Warranty',
  '1 Year Onsite warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty'],
 20)

In [15]:
df.head()

,Product Title,Product Price,Product Rating,Product Review,Product Feature
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...

In [16]:
df.columns

Index(['Product Title', 'Product Price', 'Product Rating', 'Product Review',
       'Product Feature'],
      dtype='object')

In [17]:
# Create New columns for Processor
regex = r'(?:Intel|MediaTek|Apple|AMD|Qualcomm|Snapdragon)[\s\w\(\)]+Processor(?:\s\([\d+\w+\s]+\))?'
df["Processor"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor
...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen)
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen)

In [18]:
df[df["Processor"].isna()]

Empty DataFrame
Columns: [Product Title, Product Price, Product Rating, Product Review, Product Feature, Processor]
Index: []

In [19]:
# Create New columns for RAM
regex = r"\d+\sGB[\s\w]*RAM"
df["RAM"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor,RAM
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor,16 GB LPDDR5X RAM
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor,8 GB DDR4 RAM
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor,12 GB LPDDR4X RAM
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor,8 GB DDR4 RAM
...,...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor,16 GB DDR5 RAM
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor,16 GB DDR4 RAM
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen),16 GB LPDDR5 RAM

In [20]:
df["RAM"].isna().sum()

np.int64(0)

In [21]:
# Create New columns for OS
regex = r'(?:Windows|Chrome)[\s\w]+Operating\sSystem'
df["OS"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor,RAM,OS
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor,16 GB LPDDR5X RAM,Windows 11 Operating System
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Operating System
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor,8 GB DDR4 RAM,Windows 11 Home Operating System
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor,12 GB LPDDR4X RAM,Windows 11 Operating System
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor,8 GB DDR4 RAM,Windows 11 Home Operating System
...,...,...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Home Operating System
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor,16 GB DDR5 RAM,Windows 11 Operating System
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor,16 GB DDR4 RAM,Windows 11 Home Operating System
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,Windows 11 Operating System
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen),16 GB LPDDR5 RAM,Windows 11 Operating System

In [22]:
# Create New columns for Storage
regex = r'\d+\s(?:GB|TB)\s(?:SSD|HDD)'
df["Storage"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor,RAM,OS,Storage
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor,12 GB LPDDR4X RAM,Windows 11 Operating System,512 GB SSD
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,128 GB SSD
...,...,...,...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Home Operating System,512 GB SSD
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor,16 GB DDR5 RAM,Windows 11 Operating System,1 TB SSD
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor,16 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen),16 GB LPDDR5 RAM,Windows 11 Operating System,512 GB SSD

In [23]:
# Create New columns for Display
regex = r'\d+\.\d+\scm.*Display'
df["Display"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor,RAM,OS,Storage,Display
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD,38.1 cm (15 Inch) Touchscreen Display
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 inch) Display
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 inch) Display
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor,12 GB LPDDR4X RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Display
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,128 GB SSD,29.46 cm (11.6 inch) Display
...,...,...,...,...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Home Operating System,512 GB SSD,40.64 cm (16 inch) Display
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor,16 GB DDR5 RAM,Windows 11 Operating System,1 TB SSD,35.56 cm (14 Inch) Display
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor,16 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 inch) Display
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen),16 GB LPDDR5 RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Touchscreen Display

In [24]:
# Create New columns for Warranty
regex = r'\d\sY[Year|Years|YEARS]+[\s\-\w]*(?:warranty|Warranty)'
df["Warranty"] = df['Product Feature'].apply(lambda x: re.findall(regex, x)[0] if re.findall(regex, x) else None)
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature,Processor,RAM,OS,Storage,Display,Warranty
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...,Snapdragon X Elite Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD,38.1 cm (15 Inch) Touchscreen Display,1 Year Onsite Warranty
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 inch) Display,1 Year Manufacturer Warranty
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...,Intel Core i3 Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 inch) Display,1 Year Onsite Warranty
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...,Intel Celeron Dual Core Processor,12 GB LPDDR4X RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Display,1 Year Carry-in Warranty
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...,Intel Celeron Dual Core Processor,8 GB DDR4 RAM,Windows 11 Home Operating System,128 GB SSD,29.46 cm (11.6 inch) Display,1 Year Warranty
...,...,...,...,...,...,...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...,Qualcomm Snapdragon X Processor,16 GB LPDDR5X RAM,Windows 11 Home Operating System,512 GB SSD,40.64 cm (16 inch) Display,1 Year Onsite Warranty
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...,Intel Core 7 (Series 2) Processor,16 GB DDR5 RAM,Windows 11 Operating System,1 TB SSD,35.56 cm (14 Inch) Display,1 Year Onsite Warranty
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...,Intel Core 5 Processor,16 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,1 Year Onsite Warranty
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 inch) Display,1 Year Onsite Warranty
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...,Intel Core i5 Processor (13th Gen),16 GB LPDDR5 RAM,Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Touchscreen Display,1 Year Carry-in Warranty

In [25]:
df["Product Feature"].iloc[4]

'Intel Celeron Dual Core Processor8 GB DDR4 RAM64 bit Windows 11 Home Operating System128 GB SSD29.46 cm (11.6 inch) Display1 Year Warranty'