In [10]:
import pandas as pd
import re
import numpy as np

In [2]:
df = pd.read_csv("laptop_raw_data.csv")
df

,Product Title,Product Price,Product Rating,Product Review,Product Feature
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...
...,...,...,...,...,...
979,ASUS Vivobook S16 OLED (2025) with Backlit Key...,"₹74,250",4.5,777 Ratings & 56 Reviews,Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
980,MOTOROLA Motobook 60 Full Metal OLED (i7 14th ...,"₹66,990",4.4,711 Ratings & 80 Reviews,Intel Core 7 (Series 2) Processor16 GB DDR5 RA...
981,ASUS Vivobook 15 (2025) (i5 14th Gen) with MSO...,"₹53,990",4.3,"1,231 Ratings & 90 Reviews",Intel Core 5 Processor16 GB DDR4 RAMWindows 11...
982,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹47,990",4.4,359 Ratings & 36 Reviews,Intel Core i5 Processor (12th Gen)16 GB DDR4 R...
983,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,"₹65,000",NaN,NaN,Intel Core i5 Processor (13th Gen)16 GB LPDDR5...

In [3]:
df["Product Feature"].iloc[0]

'Snapdragon X Elite Processor16 GB LPDDR5X RAMWindows 11 Operating System512 GB SSD38.1 cm (15 Inch) Touchscreen Display1 Year Onsite Warranty'

In [4]:
data = '''Intel Celeron Quad Core Processor (12th Gen)8 GB LPDDR5 RAM64 bit Windows 11 Home Operating System256 GB SSD35.81 cm (14.1 inch) DisplayWPS Office, Operating System Software1 Year Onsite Warranty
Intel Core i5 Processor (12th Gen)16 GB DDR4 RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) Display1 Year Onsite Warranty
MediaTek Kompanio 520 Processor4 GB LPDDR4X RAMChrome Operating System29.46 cm (11.6 Inch) Display1 Year Carry-in Warranty
AMD Ryzen 7 Octa Core Processor16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Carry-in Warranty
Intel Celeron Dual Core Processor8 GB DDR4 RAM64 bit Windows 11 Home Operating System512 GB SSD29.46 cm (11.6 inch) Display1 Year Warranty
Intel Celeron Dual Core Processor8 GB LPDDR4X RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) Display1 Year International Travelers Warranty (ITW)
Intel Celeron Dual Core Processor8 GB DDR4 RAM64 bit Windows 11 Home Operating System256 GB SSD29.46 cm (11.6 inch) Display1 Year Warranty
MediaTek MediaTek Kompanio 838 Processor8 GB LPDDR4X RAMChrome Operating System70.64 cm (27.81 cm) Touchscreen Display1 Year Onsite Warranty
Intel Core i3 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Carry-in Warranty
Intel Core i3 Processor (12th Gen)8 GB DDR4 RAM64 bit Windows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Domestic Warranty
Intel Core i3 Processor (13th Gen)8 GB DDR4 RAM64 bit Windows 11 Home Operating System256 GB SSD35.56 cm (14 inch) Display1 Year Warranty
AMD Ryzen 5 Hexa Core Processor16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Carry-in Warranty
Intel Core i3 Processor (13th Gen)8 GB LPDDR4X RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Onsite Warranty
Intel Core i5 Processor (12th Gen)16 GB LPDDR5 RAM64 bit Windows 11 Home Operating System1 TB SSD39.62 cm (15.6 inch) Display1 Year Onsite warranty
Intel Core i5 Processor (13th Gen)16 GB DDR5 RAMWindows 11 Home Operating System512 GB SSD35.56 cm (14 inch) DisplayMicrosoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps, McAfee 1 year1 Year Onsite Warranty
MediaTek MediaTek Kompanio 528 Processor4 GB LPDDR4X RAMChrome Operating System29.46 cm (11.6 Inch) Display1 Year Carry-in Warranty
Intel Core i7 Processor (12th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD35.56 cm (14 inch) Display1 Year Warranty Term
Intel Core i5 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Home Operating System512 GB SSD39.62 cm (15.6 inch) DisplayWindows 11 and Microsoft Office Home & Student Edition 20241 Year Carry-in Warranty
Intel Core i5 Processor (13th Gen)16 GB DDR4 RAMWindows 11 Operating System512 GB SSD39.62 cm (15.6 Inch) Display1 Year Onsite Warranty
Intel Celeron Dual Core Processor8 GB LPDDR4X RAMWindows 11 Operating System512 GB SSD35.56 cm (14 Inch) Display1 Year Carry-in Warranty'''

In [12]:
#Processor
pattern = r"(?:Intel|MediaTek|Apple|Snapdragon|Apple|AMD)[\s\w]+Processor(?:\s\([\d+\w+\s]+\))?"
res = re.findall(pattern,data)
res,len(res)

(['Intel Celeron Quad Core Processor (12th Gen)',
  'Intel Core i5 Processor (12th Gen)',
  'MediaTek Kompanio 520 Processor',
  'AMD Ryzen 7 Octa Core Processor',
  'Intel Celeron Dual Core Processor',
  'Intel Celeron Dual Core Processor',
  'Intel Celeron Dual Core Processor',
  'MediaTek MediaTek Kompanio 838 Processor',
  'Intel Core i3 Processor (13th Gen)',
  'Intel Core i3 Processor (12th Gen)',
  'Intel Core i3 Processor (13th Gen)',
  'AMD Ryzen 5 Hexa Core Processor',
  'Intel Core i3 Processor (13th Gen)',
  'Intel Core i5 Processor (12th Gen)',
  'Intel Core i5 Processor (13th Gen)',
  'MediaTek MediaTek Kompanio 528 Processor',
  'Intel Core i7 Processor (12th Gen)',
  'Intel Core i5 Processor (13th Gen)',
  'Intel Core i5 Processor (13th Gen)',
  'Intel Celeron Dual Core Processor'],
 20)

In [18]:
#RAM
pattern = r"\d+\sGB[\s\w]*RAM"
ram = re.findall(pattern,data)
ram,len(ram)

(['8 GB LPDDR5 RAM',
  '16 GB DDR4 RAM',
  '4 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '8 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '8 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '8 GB LPDDR4X RAM',
  '16 GB LPDDR5 RAM',
  '16 GB DDR5 RAM',
  '4 GB LPDDR4X RAM',
  '16 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '16 GB DDR4 RAM',
  '8 GB LPDDR4X RAM'],
 20)

In [17]:
#os
pattern = r"(?:Windows|Chrome|MacOS)[\s\w]+Operating\sSystem"
os = re.findall(pattern,data)
os,len(os)

(['Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Home Operating System',
  'Chrome Operating System',
  'Windows 11 Operating System',
  'Windows 11 Home Operating System',
  'Windows 11 Operating System',
  'Windows 11 Operating System'],
 20)

In [16]:
#storage
pattern = r"\d+\s(?:GB|TB)\s(?:SSD|HDD)"
storage = re.findall(pattern,data)
storage,len(storage)

(['256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '256 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '1 TB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD',
  '512 GB SSD'],
 17)

In [19]:
#display
pattern = r"\d+\.\d+\scm.*Display"
display = re.findall(pattern,data)
display,len(display)

(['35.81 cm (14.1 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '29.46 cm (11.6 Inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '29.46 cm (11.6 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '29.46 cm (11.6 inch) Display',
  '70.64 cm (27.81 cm) Touchscreen Display',
  '35.56 cm (14 Inch) Display',
  '35.56 cm (14 Inch) Display',
  '35.56 cm (14 inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '39.62 cm (15.6 inch) Display',
  '35.56 cm (14 inch) Display',
  '29.46 cm (11.6 Inch) Display',
  '35.56 cm (14 inch) Display',
  '39.62 cm (15.6 inch) Display',
  '39.62 cm (15.6 Inch) Display',
  '35.56 cm (14 Inch) Display'],
 20)

In [20]:
#warranty
pattern = r"\d+\sY[Years|Year]+[\s\w-]+(?:Warranty|warranty)"
warranty = re.findall(pattern,data)
warranty,len(warranty)

(['1 Year Onsite Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Warranty',
  '1 Year International Travelers Warranty',
  '1 Year Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Domestic Warranty',
  '1 Year Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Onsite Warranty',
  '1 Year Onsite warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty',
  '1 Year Warranty',
  '20241 Year Carry-in Warranty',
  '1 Year Onsite Warranty',
  '1 Year Carry-in Warranty'],
 20)

In [21]:
df.head()

,Product Title,Product Price,Product Rating,Product Review,Product Feature
0,MICROSOFT Surface Laptop (7th Edition) AI PC S...,"₹1,63,990",NaN,NaN,Snapdragon X Elite Processor16 GB LPDDR5X RAMW...
1,Samsung Galaxy Book4 Edge Series Copilot AI-PC...,"₹64,990",4.4,"2,015 Ratings & 175 Reviews",Qualcomm Snapdragon X Processor16 GB LPDDR5X R...
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹39,990",4.3,355 Ratings & 32 Reviews,Intel Core i3 Processor8 GB DDR4 RAMWindows 11...
3,Acer Aspire 3 Intel Celeron Dual Core N4500 - ...,"₹26,990",3.9,"3,574 Ratings & 275 Reviews",Intel Celeron Dual Core Processor12 GB LPDDR4X...
4,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹17,990",3.8,"7,507 Ratings & 663 Reviews",Intel Celeron Dual Core Processor8 GB DDR4 RAM...

In [22]:
df.columns

Index(['Product Title', 'Product Price', 'Product Rating', 'Product Review',
       'Product Feature'],
      dtype='object')

In [ ]:
df["Processor"] =